### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by SalitaNgDiyos** [rubiot/iBibliaMergeTool#6]
1. What happens to the original projects after merging?
2. Is it possible not to put any filter?
3. What happens if there are existing Destination/Source Texts/Associations/Notes in the destination project after merging?
3. If I merge OT and NT projects, can I still open them in iBiblia and how will it look like?

**Comment by rubiot** [comment]
1. The source project is left untouched. The destination project is modified everytime you click _"Merge Projects!"_;
2. Only the verses matched by the filter are changed. Therefore it makes no sense not to enter any filter;
3. Only the fields you've checked on the _"Field to copy"_ section will be affected;
4. Nothing will happen if you try to merge an OT project with on NT project, because the filter that matches verses in one doesn't match any on the other.

**Comment by rubiot** [comment]
I can see by your questions that the merge process is not clearly explained in the Wiki. So, let me try to clarify that:

This tool allows you to copy data from the **source project** to the **destination project**. You select what verses will be affected using the filter and you select what fields will be copied for each verse on the _"Fields to copy"_ section. Everytime you click  the button _"Merge projects!"_ the tool will find the affected range by applying the filter to both projects and, for each verse, copy the checked fields from the source to the destination project.

**Comment by SalitaNgDiyos** [comment]
Gotcha, makes more sense. Thanks!

**Comment by SalitaNgDiyos** [comment]
Ok. I got this working, but there seems to be no instruction for selecting a range of verses within a chapter only. Is there a syntax also for that? The syntax rules on the link is too complex for me to understand.

**Comment by rubiot** [comment]
You can do this using the advanced filter, just like you'd do to select multiple chapters. e.g: `John 3:(14|15|16)` to select John 3:14-16.

**Comment by SalitaNgDiyos** [comment]
Nice! Why didn't I think of that? Thanks!
